services:
  minio:
    image: minio/minio:latest
    container_name: minio_server
    ports:
      - "9000:9000"       # Port untuk akses API (digunakan script Python)
      - "9001:9001"       # Port untuk akses Dashboard Console (buka di browser)
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - ./minio_data:/data  # Folder lokal untuk menyimpan data MinIO secara permanen
    command: server /data --console-address ":9001"